(source gnu)
(source melpa)

(depends-on "dash")
(depends-on "diminish")
(depends-on "helm-ag")
(depends-on "hideshowvis")
(depends-on "popup")
(depends-on "s")
(depends-on "sbt-mode")
(depends-on "scala-mode2")
(depends-on "smartparens")
(depends-on "guide-key")
