#!/usr/bin/env bash
":"; exec emacs --quick --script "$0" "$@" # -*- mode: emacs-lisp; -*-

(load "~/.emacs.d/scripted/scripted.el")

(setq modules-root "/Users/aleksandrivanov/.emacs.d/modules"
      modules      '(;; Behavious modules
                     "behaviour/evil-core"
                     "behaviour/projectile"
                     ("behaviour/hydra" . "compile")
                     "behaviour/helm-core"
                     ("behaviour/ranger" . "compile")

                     ;; Scala
                     ("scala/sbt-mode" . ("autoloads" "all"))

                     ;; Magit
                     "vcs/magit"))

(defun compile-module (path &optional command)
  (let ((default-directory (concat modules-root "/" path))
        (compilation-buffer-name-function (lambda (mode-name) (format "*COMPILE-%s-%s*" path command))))
    (message "Compiling module: %s with '%s'" default-directory command)
    (cond ((not command) (compile "make -k"))
          (t (compile (format "make %s" command))))))

;; Run the script
(-each modules
  (lambda (module)
    (pcase module
      (`(,path . ,command)
       (cond ((stringp command) (compile-module path command))
             ((listp command) (-each command (lambda (cmd) (compile-module path cmd))))))
      (path (compile-module path)))))

